import mongoose from "mongoose";

const PerformanceSchema = new mongoose.Schema(
  {
    studentId: { type: String, required: true, index: true },
    studentname: { type: String, required: true, index: true },
    class: { type: String, required: true, index: true },
    section: { type: String, required: true, index: true },
    stream: { type: String, required: true, index: true },
    schoolname: { type: String, required: true, index: true },
    branch: { type: String, required: true, index: true },
    schoolId: { type: String, required: true, index: true },
    region: { type: String, required: true, index: true },
    district: { type: String, required: true, index: true },
    parentContact: { type: String, required: true, index: true },
    omrCode: { type: String, required: true, index: true },
    SUBJECT1: { type: String, default: 0 },
    SUBJECT2: { type: String, default: 0 },
    SUBJECT3: { type: String, default: 0 },
    SUBJECT4: { type: String, default: 0 },
    SUBJECT5: { type: String, default: 0 },
    subject1: { type: String, default: 0 },
    subject2: { type: String, default: 0 },
    subject3: { type: String, default: 0 },
    subject4: { type: String, default: 0 },
    subject5: { type: String, default: 0 },
    fullmark: { type: String, default: 0 },
    nationalrank: String,
    regionrank: String,
    districtrank: String,
    SAVGTOT: String,
    SAVGSUB1: String,
    SAVGSUB2: String,
    SAVGSUB3: String,
    SAVGSUB4: String,
    SAVGSUB5: String,
    DAVGTOT: String,
    DAVGSUB1: String,
    DAVGSUB2: String,
    DAVGSUB3: String,
    DAVGSUB4: String,
    DAVGSUB5: String,
    RAVGTOT: String,
    RAVGSUB1: String,
    RAVGSUB2: String,
    RAVGSUB3: String,
    RAVGSUB4: String,
    RAVGSUB5: String,
    NAVGTOT: String,
    NAVGSUB1: String,
    NAVGSUB2: String,
    NAVGSUB3: String,
    NAVGSUB4: String,
    NAVGSUB5: String,
  },
  { timestamps: true, collection: "results" }
);

export const Performance =
  mongoose.models.Performance || mongoose.model("Performance", PerformanceSchema);
