// Mock data for regions and districts
export const regions = [
  { value: "1", label: "East UP" },
  { value: "2", label: "West UP" },
  { value: "3", label: "Bihar" },
  { value: "4", label: "Jharkhand" },
  { value: "5", label: "Uttarakhand" },
];

export const districts = {
  "1": [ /* EAST UP */
    { value: "01", label: "Allahabad" },
    { value: "02", label: "Ambedkar Nagar" },
    { value: "03", label: "Amethi" },
    { value: "04", label: "Auraiya" },
    { value: "05", label: "Ayodhya" },
    { value: "06", label: "Azamgarh" },
    { value: "07", label: "Bahraich" },
    { value: "08", label: "Ballia" },
    { value: "09", label: "Balrampur" },
    { value: "10", label: "Banda" },
    { value: "11", label: "Barabanki" },
    { value: "12", label: "Basti" },
    { value: "13", label: "Bhadohi" },
    { value: "14", label: "Chandauli" },
    { value: "15", label: "Chitrakoot" },
    { value: "16", label: "Deoria" },
    { value: "17", label: "Etawah" },
    { value: "18", label: "Farrukabad" },
    { value: "19", label: "Fatehpur" },
    { value: "20", label: "Gangapar" },
    { value: "21", label: "Ghazipur" },
    { value: "22", label: "Gonda" },
    { value: "23", label: "Gorakhpur" },
    { value: "24", label: "Hamirpur" },
    { value: "25", label: "Hardoi" },
    { value: "26", label: "Jalaun" },
    { value: "27", label: "Jaunpur" },
    { value: "28", label: "Jhansi" },
    { value: "29", label: "Kannauj" },
    { value: "30", label: "Kanpur City" },
    { value: "49", label: "Kanpur Dehat" },
    { value: "31", label: "Kaushambi" },
    { value: "32", label: "Kushinagar" },
    { value: "33", label: "Lalitpur" },
    { value: "34", label: "Lucknow" },
    { value: "35", label: "Maharajganj" },
    { value: "36", label: "Mahoba" },
    { value: "37", label: "Mau" },
    { value: "38", label: "Mirzapur" },
    { value: "39", label: "Pratapgarh" },
    { value: "40", label: "Rae Bareli" },
    { value: "41", label: "Sant Kabir Nagar" },
    { value: "42", label: "Shravasti" },
    { value: "43", label: "Siddhartha nagar" },
    { value: "44", label: "Sitapur" },
    { value: "45", label: "Sonbhadra" },
    { value: "46", label: "Sultanpur" },
    { value: "47", label: "Unnao" },
    { value: "48", label: "Varanasi" },
  ],
  "2": [ /* WEST UP */
    { value: "01", label: "Agra" },
    { value: "02", label: "Aligarh" },
    { value: "03", label: "Amroha" },
    { value: "04", label: "Badaun" },
    { value: "05", label: "Baghpat" },
    { value: "06", label: "Bareilly" },
    { value: "07", label: "Bijnor" },
    { value: "08", label: "Bulandshahr" },
    { value: "09", label: "Etah" },
    { value: "10", label: "Firozabad" },
    { value: "11", label: "Hapur" },
    { value: "12", label: "Hathras" },
    { value: "13", label: "Kasganj" },
    { value: "14", label: "Lakhimpur Kheri" },
    { value: "15", label: "Mainpuri" },
    { value: "16", label: "Mathura" },
    { value: "17", label: "Meerut" },
    { value: "18", label: "Moradabad" },
    { value: "19", label: "Muzzafarnagar" },
    { value: "20", label: "Pilibhit" },
    { value: "21", label: "Rampur" },
    { value: "22", label: "Saharanpur" },
    { value: "23", label: "Sambhal" },
    { value: "24", label: "Shahjahanpur" },
    { value: "25", label: "Shamli" },
  ],
  "3": [ // Bihar
    { value: "01", label: "Ara" },
    { value: "02", label: "Araria" },
    { value: "03", label: "Arwal" },
    { value: "04", label: "Aurangabad" },
    { value: "05", label: "Banka" },
    { value: "06", label: "Begusarai" },
    { value: "07", label: "Bettiah" },
    { value: "08", label: "Bhagalpur" },
    { value: "09", label: "Biharsharif" },
    { value: "10", label: "Buxar" },
    { value: "11", label: "Chapra" },
    { value: "12", label: "Darbhanga" },
    { value: "13", label: "Gaya" },
    { value: "14", label: "Gopalganj" },
    { value: "15", label: "Hajipur" },
    { value: "16", label: "Jamui" },
    { value: "17", label: "Jehanabad" },
    { value: "18", label: "Kaimur" },
    { value: "19", label: "Katihar" },
    { value: "20", label: "Khagaria" },
    { value: "21", label: "Kishanganj" },
    { value: "22", label: "Lakhisarai" },
    { value: "23", label: "Madhepura" },
    { value: "24", label: "Madhubani" },
    { value: "25", label: "Motihari" },
    { value: "26", label: "Munger" },
    { value: "27", label: "Muzaffarpur" },
    { value: "28", label: "Nawada" },
    { value: "29", label: "Patna" },
    { value: "30", label: "Purnea" },
    { value: "31", label: "Rohtas" },
    { value: "32", label: "Saharsa" },
    { value: "33", label: "Samastipur" },
    { value: "34", label: "Sheikhpura" },
    { value: "35", label: "Sheohar" },
    { value: "36", label: "Sitamarhi" },
    { value: "37", label: "Siwan" },
    { value: "38", label: "Supaul" }
  ],
  "4": [ // Jharkhand
    { value: "01", label: "Bokaro" },
    { value: "02", label: "Chatra" },
    { value: "03", label: "Deoghar" },
    { value: "04", label: "Dhanbad" },
    { value: "05", label: "Dumka" },
    { value: "06", label: "East Singhbhum" },
    { value: "07", label: "Garhwa" },
    { value: "08", label: "Giridih" },
    { value: "09", label: "Godda" },
    { value: "10", label: "Gumla" },
    { value: "11", label: "Hazaribagh" },
    { value: "12", label: "Jamtara" },
    { value: "13", label: "Khunti" },
    { value: "14", label: "Kodarma" },
    { value: "15", label: "Latehar" },
    { value: "16", label: "Lohardaga" },
    { value: "17", label: "Pakur" },
    { value: "18", label: "Palamu" },
    { value: "19", label: "Ramgarh" },
    { value: "20", label: "Ranchi" },
    { value: "21", label: "Sahibganj" },
    { value: "22", label: "Saraikela-Kharsawan" },
    { value: "23", label: "Simdega" },
    { value: "24", label: "West Singhbhum" }
  ],
  "5": [ // Uttarakhand
    { value: "01", label: "Almora" },
    { value: "02", label: "Bageshwar" },
    { value: "03", label: "Chamoli" },
    { value: "04", label: "Champawat" },
    { value: "05", label: "Dehradun" },
    { value: "06", label: "Haldwani" },
    { value: "07", label: "Haridwar" },
    { value: "08", label: "Nainital" },
    { value: "09", label: "Pauri Garhwal" },
    { value: "10", label: "Pithoragarh" },
    { value: "11", label: "Rishikesh" },
    { value: "12", label: "Roorkee" },
    { value: "13", label: "Rudraprayag" },    
    { value: "14", label: "Tehri Garhwal" },  
    { value: "15", label: "Udham Singh Nagar" },
    { value: "16", label: "Uttarkashi" },
    { value: "17", label: "Vikas Nagar" },
  ],
}

// Routes
export const ROUTES = {
  HOME: "/",
  TEAM: "/team",
  TEAM_VIEW: "/team/view",
  TEAM_ADD: "/team/add",
  TEAM_EDIT: "/team/edit",
  TEAM_VIEW_STUDENTS: "/team/view-students",
  TEAM_ADD_SCHOOL: "/team/add-school",
}
export const API_ROUTES = {
  SCHOOLS: "/api/schools",
  STUDENTS: "/api/students",
  SCHOOL_COORDINATORS: "/api/school-coordinators",
  TEAM_MEMBERS: "/api/team-members",
}